Fix #785: add squash support
fabric8io/docker-maven-plugin pull request #1366
Opened 2020-08-03 01:07 UTC by dexterhu

* allow to squash docker images from config in pom.xml
```
<buildOptions>
        <squash>1</squash>
</buildOptions>
```
* default is disabled.

2020-08-03 05:34 UTC, dexterhu commented
tested with a SNAPSHOT release at https://github.com/dexterhu/docker-maven-plugin/packages/340297?version=0.34-SNAPSHOT

2020-08-03 07:42 UTC, rhuss commented
Thanks ! I will try to have a look after my PTO (which starts now) in 2 weeks ...

2020-08-30 15:17 UTC, rhuss requested changes
Thanks ! looks good to me, with some minor cosmetic suggestions. I think we can merge this soon.

2020-08-30 15:17 UTC, rhuss commented on pom.xml
> +  <version>0.34-SNAPSHOT</version>
we are still on 0.33-SNAPSHOT ...

2020-08-30 15:17 UTC, rhuss commented on src/main/asciidoc/inc/external/_property_configuration.adoc
> +| Squash newly built layers into a single new layer (API 1.25+, need to enable it in Daemon configuration file)
```suggestion
| Squash newly built layers into a single layer (API 1.25+, needs to be enabled in the Docker daemon configuration)
```

2020-08-30 15:32 UTC, rhuss commented
Could you please also add an entry to the changelog.md ? thanks !

2020-08-31 04:52 UTC, dexterhu commented on pom.xml
> +  <version>0.34-SNAPSHOT</version>
rolled back to 0.33-SNAPSHOT

2020-08-31 04:53 UTC, dexterhu commented on src/main/asciidoc/inc/external/_property_configuration.adoc
> +| Squash newly built layers into a single new layer (API 1.25+, need to enable it in Daemon configuration file)
updated.

2020-08-31 04:55 UTC, dexterhu commented
> Could you please also add an entry to the changelog.md ? thanks !

added a new item under `0.33-SNAPSHOT` in changelog.md

2020-08-31 06:50 UTC, merged